#!/bin/bash

# bashRunner: a simple task runner written in Bash
# Copyright 2013 Andrew Gilbert
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# This script should be started automatically on user login via
# /etc/xdg/autostart/script.desktop or equivalent.

APP_PATH="/apps/startupscript/"
DEBUG=false

function write_key () {
	# Arguments:
	# $1: name of task
	# $2: what to write
	if $DEBUG
	then
		echo "Writing $APP_PATH$1 as $2" >&2
	fi
	dconf write "$APP_PATH$1" "$2"
}

function read_key () {
	# Arguments:
	# $1: name of task
	local r="$(dconf read "$APP_PATH$1")"
	if $DEBUG
	then
		echo "Read $APP_PATH$1 as $r" >&2
	fi
	echo "$r"
}

function reset_key () {
	# Arguments:
	# $1: name of task
	if $DEBUG
	then
		echo "Resetting $APP_PATH$1" >&2
	fi
	dconf reset "$APP_PATH$1"
}

function task () {
	# Arguments:
	# $1: name of task
	# $2: task to run
	# $3: run multiple
	if [ -z "$1" ]
	then
		exit 14
	fi

	if [ "$3" == "repeat" ]
	then
		local count="$(read_key "$1")"
		let count++
		echo -n "Doing $1..."

		# Substitute the run count for %c in the command
		local cmd="${2//'%c'/$count}"
		# Substitute % for %% in the command
		local cmd="${cmd//'%%'/'%'}"

		# If the task completes successfully, add a count
		eval "$cmd" && write_key "$1" "$count"
		echo -e "\t        DONE (historical total: $count)"
	elif [ "$3" == "clear" ]
	then
		reset_key "$1"
	else
		local status="$(read_key "$1")"

		# If the task hasn't been run before...
		if [ "$status" != "'done'" ]
		then
			echo -n "Doing $1 for the only time..."
			eval "$2" && write_key "$1" "'done'"
		else
			echo "Not doing "$1" as it's been done already."
		fi
	fi
}

# TASK FUNCTIONS
function demo () {
	zenity --question --text="Press yes to complete this task. Press no to fail to complete this task."
}

# TASK LIST
# Format:
#   task "taskName" "taskFunction" ["option"]
# Options:
#   "repeat":
#     Run this task every time bashRunner is run.
#   "clear":
#     Reset the runcount of this task so it will run again.
#   (none):
#     Run the task on first run of bashRunner only.
task "showOff" "demo"

# When in debug mode, run tasks specified on the command line
if $DEBUG
then
	while [ -n "$1" -a -n "$2" -a -n "$3" ]
	do
		task "$1" "$2" "$3"
		shift
		shift
		shift
	done
fi
